language: node_js
cache:
  directories:
    - node_modules
before_script:
- ./scripts/prebuild.sh
node_js:
- 6
sudo: false
deploy:
  provider: pages
  local-dir: out/
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: develop
env:
  global:
  - GH_REPO="andrewchumchal/AndrewChumchal.com"
# GH_TOKEN is set in travis's web ui now, username & email are set in scripts/deploy.sh
